<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../XsltTestMediator.wsdl"/>
      <rootElement name="Request" namespace="http://soa.cookbook.xpath"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../AssignTestMediator.wsdl"/>
      <rootElement name="Response" namespace="http://soa.cookbook.xpath"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [THU AUG 11 20:09:02 MDT 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:blog="http://www.oracle.com/XSL/Transform/java/antony.blog.XPathImpl"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/SOACookbookChapter8/XPathTest/XsltTestMediator"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.oracle.com/SOACookbookChapter8/XPathTest/AssignTestMediator"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:stat="http://www.oracle.com/XSL/Transform/java/soa.cookbook.xpath.StdDev"
                xmlns:inp1="http://soa.cookbook.xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns wsdl xsd inp1 ns0 blog bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn stat ldap">
  <xsl:template match="/">
    <inp1:Response>
      <inp1:Request>
        <xsl:for-each select="/inp1:Request/inp1:Data">
          <inp1:Data>
            <xsl:value-of select="."/>
          </inp1:Data>
        </xsl:for-each>
      </inp1:Request>
      <inp1:XsltStdDev>
        <xsl:value-of select="stat:getStdDev(/inp1:Request/inp1:Data)"/>
      </inp1:XsltStdDev>
    </inp1:Response>
  </xsl:template>
</xsl:stylesheet>
