<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Echo"
     targetNamespace="http://xmlns.oracle.com/SOACookbookSecurity/EchoApplication/Echo"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://soa.cookbook"
     xmlns:tns="http://xmlns.oracle.com/SOACookbookSecurity/EchoApplication/Echo"
    >
    <plnk:partnerLinkType name="Echo">
        <plnk:role name="EchoProvider" portType="tns:echo_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://soa.cookbook" schemaLocation="xsd/echo.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="input" element="inp1:request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="output" element="inp1:response"/>
    </wsdl:message>
    <wsdl:portType name="echo_ptt">
        <wsdl:operation name="echo">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
