<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../SpringMediator.wsdl"/>
      <rootElement name="Employee" namespace="http://soa.cookbook/Employee"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../EmployeeEJBBean.wsdl"/>
      <rootElement name="addEmployee" namespace="http://cookbook.soa/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [THU DEC 27 18:13:42 MST 2012]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:inp1="http://soa.cookbook/Employee"
                xmlns:tns="http://xmlns.oracle.com/SOACookbookChapter8/SpringSample/SpringMediator"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns0="http://cookbook.soa/types"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://cookbook.soa/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:stat="http://www.oracle.com/XSL/Transform/java/soa.cookbook.xpath.StdDev"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl inp1 tns wsdl xsd soap12 soap mime ns0 ns1 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn stat ldap">
  <xsl:template match="/">
    <ns1:addEmployee>
      <arg0>
        <ENum>
          <xsl:value-of select="/inp1:Employee/inp1:EmployeeNumber"/>
        </ENum>
        <address>
          <addr>
            <xsl:value-of select="/inp1:Employee/inp1:Address/inp1:Addr1"/>
          </addr>
          <city>
            <xsl:value-of select="/inp1:Employee/inp1:Address/inp1:Addr2"/>
          </city>
        </address>
        <name>
          <xsl:value-of select="/inp1:Employee/inp1:Name"/>
        </name>
        <phone>
          <xsl:value-of select="/inp1:Employee/inp1:Phone"/>
        </phone>
      </arg0>
    </ns1:addEmployee>
  </xsl:template>
</xsl:stylesheet>
