<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="WarehouseService"
     targetNamespace="http://rubiconred.com/ckbk/svc/WarehouseService"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://rubiconred.com/ckbk/svc/WarehouseService"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="WarehouseService">
        <plnk:role name="WarehouseService">
            <plnk:portType name="tns:WarehouseService"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://rubiconred.com/ckbk/svc/WarehouseService" location="WarehouseService_1.0.wsdl"/>
</wsdl:definitions>
