<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../EXM_Mapping_EJB.wsdl"/>
      <rootElement name="getQuotesResponse" namespace="http://cookbook.soa/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../QuoteService.wsdl"/>
      <rootElement name="quoteResponse" namespace="http://cookbook.soa.mapping/types"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [WED SEP 28 12:27:22 MDT 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:blog="http://www.oracle.com/XSL/Transform/java/antony.blog.XPathImpl"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:inp1="http://cookbook.soa.mapping/types"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://soa.cookbook.mapping/QuoteService"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://cookbook.soa.mapping/javatypes"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://cookbook.soa/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:stat="http://www.oracle.com/XSL/Transform/java/soa.cookbook.xpath.StdDev"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap12 soap mime wsdl ns0 xsd tns inp1 ns1 blog bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn stat ldap">
  <xsl:template match="/">
    <inp1:quoteResponse>
      <xsl:for-each select="/tns:getQuotesResponse/response/ns0:quotes">
        <inp1:quote>
          <inp1:product>
            <xsl:value-of select="ns0:product"/>
          </inp1:product>
          <inp1:vendorQuotes>
            <xsl:for-each select="ns0:vendors/ns0:hwVendorQuote">
              <inp1:hardwareQuote>
                <inp1:price>
                  <xsl:value-of select="ns0:price"/>
                </inp1:price>
                <inp1:vendor>
                  <xsl:value-of select="ns0:vendor"/>
                </inp1:vendor>
                <inp1:hardwareItemList>
                  <xsl:for-each select="ns0:items">
                    <inp1:hardwareItem>
                      <inp1:item>
                        <xsl:value-of select="ns0:item"/>
                      </inp1:item>
                      <inp1:airTransportable>
                        <xsl:value-of select="ns0:airTransportable"/>
                      </inp1:airTransportable>
                      <inp1:price>
                        <xsl:value-of select="ns0:price"/>
                      </inp1:price>
                      <inp1:quantity>
                        <xsl:value-of select="ns0:quantity"/>
                      </inp1:quantity>
                    </inp1:hardwareItem>
                  </xsl:for-each>
                </inp1:hardwareItemList>
              </inp1:hardwareQuote>
            </xsl:for-each>
            <xsl:for-each select="ns0:vendors/ns0:svcVendorQuote">
              <inp1:serviceQuote>
                <inp1:price>
                  <xsl:value-of select="ns0:price"/>
                </inp1:price>
                <inp1:vendor>
                  <xsl:value-of select="ns0:vendor"/>
                </inp1:vendor>
                <inp1:serviceItemList>
                  <xsl:for-each select="ns0:items">
                    <inp1:serviceItem>
                      <inp1:service>
                        <xsl:value-of select="ns0:service"/>
                      </inp1:service>
                      <inp1:details>
                        <xsl:value-of select="ns0:details"/>
                      </inp1:details>
                      <inp1:price>
                        <xsl:value-of select="ns0:price"/>
                      </inp1:price>
                    </inp1:serviceItem>
                  </xsl:for-each>
                </inp1:serviceItemList>
              </inp1:serviceQuote>
            </xsl:for-each>
          </inp1:vendorQuotes>
        </inp1:quote>
      </xsl:for-each>
    </inp1:quoteResponse>
  </xsl:template>
</xsl:stylesheet>
