<?binding.jca InsertTestTableService_db.jca?>
<wsdl:definitions name="InsertTestTableService" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOACookbookTransaction/SingleTransactionTest/InsertTestTableService" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOACookbookTransaction/SingleTransactionTest/InsertTestTableService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertTestTableService">
    <plt:partnerLinkType name="InsertTestTableService_plt">
        <plt:role name="InsertTestTableService_role">
            <plt:portType name="tns:InsertTestTableService_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertTestTableService" schemaLocation="xsd/InsertTestTableService_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="TestTableCollection_msg">
        <wsdl:part name="TestTableCollection" element="top:TestTableCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertTestTableService_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TestTableCollection_msg"/>
            <wsdl:output message="tns:TestTableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
