<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SingleTransactionService"
     targetNamespace="http://oracle.com/sca/soapservice/SOACookbookTransaction/SingleTransactionTest/SingleTransactionService"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://soa.cookbook/Transactions"
     xmlns:tns="http://oracle.com/sca/soapservice/SOACookbookTransaction/SingleTransactionTest/SingleTransactionService"
    >
    <plnk:partnerLinkType name="SingleTransactionService">
        <plnk:role name="SingleTransactionServiceProvider" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://soa.cookbook/Transactions" schemaLocation="xsd/TransactionID.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:TransactionRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="response" element="inp1:TransactionResponsePair"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
