<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ArrayProcess.wsdl"/>
      <rootElement name="quotes" namespace="http://xmlns.oracle.com/SOACookbookMapping/ArrayProcessing/ArrayProcess"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ArrayProcess.wsdl"/>
      <rootElement name="lowestQuotes" namespace="http://xmlns.oracle.com/SOACookbookMapping/ArrayProcessing/ArrayProcess"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [THU AUG 02 13:46:41 MDT 2012]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:blog="http://www.oracle.com/XSL/Transform/java/antony.blog.XPathImpl"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:client="http://xmlns.oracle.com/SOACookbookMapping/ArrayProcessing/ArrayProcess"
                xmlns:stat="http://www.oracle.com/XSL/Transform/java/soa.cookbook.xpath.StdDev"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plnk xsd wsdl client bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <client:lowestQuotes>
      <xsl:for-each select="/client:quotes/client:productQuote">
        <client:productLowestQuote>
          <client:productName>
            <xsl:value-of select="client:productName"/>
          </client:productName>
          <client:vendors>
            <xsl:for-each select="client:vendors/client:vendorQuote">
              <xsl:sort select="client:price" data-type="number"/>
              <client:vendorQuote>
                <client:vendorName>
                  <xsl:value-of select="client:vendorName"/>
                </client:vendorName>
                <client:price>
                  <xsl:value-of select="client:price"/>
                </client:price>
              </client:vendorQuote>
            </xsl:for-each>
          </client:vendors>
          <client:lowestPrice>
            <xsl:value-of select="oraext:min-value-among-nodeset(client:vendors/client:vendorQuote/client:price)"/>
          </client:lowestPrice>
        </client:productLowestQuote>
      </xsl:for-each>
    </client:lowestQuotes>
  </xsl:template>
</xsl:stylesheet>
